Training/Models/Class.cs
using System.ComponentModel;

namespace Training.Models
{
    public class Class
    {
        public int Id { get; set; }
        [DisplayName("Mã Lớp :")]
        public  string MaLop { get; set; }
        [DisplayName("Tên Lớp :")]
        public string TenLop { get; set; }
    }
}

Training/Models/ErrorViewModel.cs
using System;

namespace Training.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Training/Models/Student.cs
using System.ComponentModel;

namespace Training.Models
{
    public  class Student
    {
      
        public int Id { get; set; }
        [DisplayName("Mã sinh viên :")]
        public string MaSV { get; set; }
        [DisplayName("Họ Tên :")]
        public string HoTen { get; set; }
    }
}

Training/Models/TrainingDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Training.Models
{
    public class TrainingDbContext : DbContext
    {
        public TrainingDbContext(DbContextOptions options) : base(options)
        {

        }

        public DbSet<Student> Student { get; set; }
        public DbSet<Class> Class { get; set; }

    }
}

Training/Controllers/ClassController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Training.Models;
using Training.Service;

namespace Training.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassService _classService;

        public ClassController (IClassService classService)
        {
            _classService = classService;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            return View(_classService.GetAll());
        }
       
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(Class class1)
        {
            
            if(ModelState.IsValid)
            {
                _classService.Create(class1);
                _classService.save();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            return View(_classService.GetById(Id));
        }
        public IActionResult Delete(int Id)
        {
            _classService.Delete(Id);
            _classService.save();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(int? Id)
        { 
            return View(_classService.GetById(Id));
        }
        public async Task<IActionResult> Edit(Class class1)
        { 
            _classService.Update(class1);
            _classService.save();
            return RedirectToAction("Index");

        }
        
        [HttpGet]
        public IActionResult GetId()
        {
            return View();
        }
        
    }
}

Training/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Internal;
using Microsoft.AspNetCore.Mvc;
using Training.Models;
using Training.Service;

namespace Training.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
            
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
   
    }
}

Training/Controllers/StudentController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Training.Models;
using Training.Service;

namespace Training.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            return View(_studentService.GetAll());
        }
       
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create( Student student)
        {
           
            if(ModelState.IsValid)
            {
                _studentService.Create(student);
                _studentService.save();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            return View(_studentService.GetById(Id));
        }
        public IActionResult Delete(int Id)
        {
            _studentService.Delete(Id);
            _studentService.save();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(int? Id)
        { 
            return View(_studentService.GetById(Id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Student student)
        { 
            _studentService.Update(student);
            _studentService.save();
            return RedirectToAction("Index");

        }

    }
}

Training/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Training.Models;
using Training.Service;
using Training.UnitOfWork;

namespace Training.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork  unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
//         GET
        [HttpGet]
        public IActionResult Create()
        {

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(Class class1)
        {
            var student = new Student()
            {
                MaSV = Request.Form["MaSV"],
                HoTen = Request.Form["HoTen"],
            };
            var classs = new Class()
            {
                MaLop = Request.Form["MaLop"],
                TenLop = Request.Form["TenLop"]
            };
        if(ModelState.IsValid)
            {
               _unitOfWork.classRepository.Create(classs);
               _unitOfWork.studentRepository.Create(student);
               _unitOfWork.save();
              
                return RedirectToAction("Create");
            }
            return RedirectToAction("Create");
        }

       

        public IActionResult Edit()
        {
            throw new System.NotImplementedException();
        }
    }

    internal class ClasstService
    {
    }
}

Training/Views/Class/Create.cshtml
@model Class
<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Thêm em vô đi anh yêu :</p>
<div class="container-fluid">
    <div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px" >
        <form asp-action="Create" method="post">
            @* <input type="hidden" name="requestpath" id="requestpath"  /> *@
            <div class="form-group row ">
                <label asp-for="MaLop" class="col-md-4"></label>
                <div class="col-md-5">
                    <input  asp-for="MaLop" style="width: 200px"class="form-control" type="text" placeholder="Nhập Mã sinh viên"required />
                </div>
                   
            </div>
          
            <div class="form-group row">
                <label asp-for="TenLop" class="col-md-4"></label>
                <div class="col-md-5">
                    <input asp-for="TenLop" style="width: 200px"class="form-control" type="text" placeholder="Nhập Họ tên" required />
                </div>
                   
            </div>
                
            <div class="form-group ">
                <input class="btn btn-primary" type="submit" value="Create"style="margin-right: 10px; border-radius: 5px" />
                <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
            </div>
        
        </form>
    </div>
</div>

Training/Views/Class/Delete.cshtml
@model Class
<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Anh muốn xóa em sao ?</p>
<div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px">
<dl class="row" >
    <dt class="col-md-4" style="color: #fff">
        @Html.DisplayNameFor(model => model.MaLop)
    </dt>
    <dd class="col-md-5"style="color: #fff">
        @Html.DisplayFor(model => model.MaLop)
    </dd>
    <dt class="col-md-4"style="color: #fff">
        @Html.DisplayNameFor(model => model.TenLop)
    </dt>
    <dd class="col-md-5"style="color: #fff">
        @Html.DisplayFor(item => item.TenLop)
    </dd>
</dl>
<div style="padding: 10px 0">
    <div >
        <form asp-action="Delete" >
            <input  asp-for="Id" type="hidden"  />
            <input class="btn btn-primary" type="submit" value="Delete" style="border-radius: 5px; margin-right: 10px;"  />
            <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
        </form>
    </div>
    
</div>
</div>
@* $1$ </form> #1# *@
@* *@
@* <h1>Delete</h1> *@
@* *@
@* <h3>Are you sure you want to delete this?</h3> *@
@* <div> *@
@*     <h4>User</h4> *@
@*     <hr /> *@
@*     <dl class="row"> *@
@*         <dt class = "col-sm-2"> *@
@*             @Html.DisplayNameFor(model => model.HoTen) *@
@*         </dt> *@
@*         <dd class = "col-sm-10"> *@
@*             @Html.DisplayFor(model => model.UserName) *@
@*         </dd> *@
@*         <dt class = "col-sm-2"> *@
@*             @Html.DisplayNameFor(model => model.Password) *@
@*         </dt> *@
@*         <dd class = "col-sm-10"> *@
@*             @Html.DisplayFor(model => model.Password) *@
@*         </dd> *@
@*     </dl> *@
@*      *@
@*     <form asp-action="Delete"> *@
@*         <input type="hidden" asp-for="Id" /> *@
@*         <input type="submit" value="Delete" class="btn btn-danger" /> | *@
@*        *@
@*     </form> *@
@* </div> *@

Training/Views/Class/Edit.cshtml
@model Class


<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Anh muốn thay đổi em sao, anh không còn yêu em à ?</p>
@* <form> *@
    <div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px" >
        <div style=" width: 100%" >
            <form asp-action="Edit" >
                <div class="form-group row ">
                    <label asp-for="MaLop" class="col-md-4"></label>
                    <div class="col-md-8">
                        <input  asp-for="MaLop" style="width: 200px"class="form-control" type="text"  />
                    </div>
                   
                </div>
                <div class="form-group row">
                    <label asp-for="TenLop" class="col-md-4"></label>
                    <div class="col-md-8">
                        <input asp-for="TenLop" style="width: 200px"class="form-control" type="text" />
                    </div>
                   
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group " style="padding-top: 20px">
                    <input class="btn btn-primary" type="submit" value="Update" style="margin-right: 10px; border-radius: 5px"  />
                    <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
                </div>
            </form>
        </div>
    </div>
@* </form> *@

Training/Views/Class/GetId.cshtml
@model Class

@{
    ViewData["Title"] = "Hello anh đẹp trai";
}

<h1>@ViewData["Title"]</h1>
<p style="text-align: left">Anh lại nhớ em rồi à <br /> Sao đến giờ anh mới chịu tìm em  anh yêu ? </p>
@* <form> *@
<div class="container-fluid">
    <div >
        <form asp-action="GetId" method="post">
            @* <input type="hidden" name="requestpath" id="requestpath"  /> *@
            <div class="form-group row ">
                <label asp-for="Id" class="col-md-3">Tìm kiếm bằng mã Id : </label>
                <div class="col-md-5">
                    <input  asp-for="Id" style="width: 200px"class="form-control" type="text" placeholder="Nhập Id"required />
                </div>
                   
            </div> 
            <div class="form-group ">
                <input class="btn btn-primary" type="submit" value="GetId" style="padding-right:10px " />
                <a class="btn btn-primary" asp-action="Index">Cancel</a>   
            </div>
        </form>
        
    </div>
</div>
@* </form> *@

Training/Views/Class/Index.cshtml
@model IEnumerable<Class>

@{
    ViewData["Title"] = "Hello anh đẹp trai";
}


<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Danh sách Lớp</h1>

 <div >
          <div class="tm-bg-primary-dark tm-block tm-block-products">
            <div class="tm-product-table-container">
              <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                <tr>
                    <th scope="col">&nbsp;</th>
                    <th scope="col" style="text-transform: uppercase">@Html.DisplayNameFor(model => model.MaLop)</th>
                    <th scope="col" style="text-transform: uppercase">@Html.DisplayNameFor(model => model.TenLop)</th>
                    <th scope="col">&nbsp;</th>
                </tr>
                </thead>
                  <tbody>
                  @foreach (var item in Model)
                  {
                      <tr>
                          <td scope="col">&nbsp;</td>
                          <td>
                              @Html.DisplayFor(modelItem => item.MaLop)
                          </td>
                          <td>
                              @Html.DisplayFor(modelItem => item.TenLop)
                          </td>
                          <td>
                              <a asp-action="Edit" asp-route-id="@item.Id" class="tm-product-delete-link" style="margin-right: 10px;">
                                  <i class="fa fa-pencil"></i>
                              </a>
                              <a asp-action="Delete" asp-route-id="@item.Id" class="tm-product-delete-link">
                                  <i class="fa fa-trash"></i>
                              </a>
                          </td>
                          
                      </tr>
                  }
                  </tbody>
              </table>
            </div>
            <!-- table container -->
            <a
                asp-action="Create"
                class="btn btn-primary btn-block text-uppercase mb-3">Add new class <i class="fa fa-user-plus" style="font-size: 20px; "></i>
                </a>
          
          </div>
    </div>

Training/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Training/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - Training</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    <!-- https://fonts.google.com/specimen/Roboto -->
    @* <link rel="stylesheet" href="~/css/fontawesome.min.css"> *@
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="~/css/templatemo-style.css">
</head>
<body>
    <header>
      
        <nav class="navbar navbar-expand-xl">
            <div class="container h-100" >
                <a class="navbar-brand" href="index.html">
                    <h1 class="tm-site-title mb-0">Trang Đào Tạo</h1>
                </a>
                <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars tm-nav-icon"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto h-100">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <i class="fa fa-home"></i>
                               TRANG CHỦ
                            </a>
                        </li>
                        <li class="nav-item ">

                            <a class="nav-link " asp-controller="Home" asp-action="Privacy" >
                                <i class="fa fa-user-secret"></i>
                                <span>
                                BẢO MẬT
                                </span>
                            </a>
     
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Student" asp-action="Index" >
                                <i class="fa fa-graduation-cap"></i>
                                <span>
                                   SINH VIÊN
                                </span>
                            </a>
                           
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Class" asp-action="Index">
                                <i class="fa fa-university"></i>
                                <span>
                                    LỚP
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="User" asp-action="Create">
                                <i class="fa fa-users"></i>
                                <span>
                                    USER
                                </span>
                            </a>
                        </li>
                        </ul>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Training - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        
        <script src="~/js/jquery-3.3.1.min.js"></script>
        <!-- https://jquery.com/download/ -->
        <script src="~/js/moment.min.js"></script>
        <!-- https://momentjs.com/ -->
        <script src="~/js/Chart.min.js"></script>
        <!-- http://www.chartjs.org/docs/latest/ -->
        <script src="~/js/bootstrap.min.js"></script>
        <!-- https://getbootstrap.com/ -->
        <script src="~/js/tooplate-scripts.js"></script>
        <script>
            Chart.defaults.global.defaultFontColor = 'white';
            let ctxLine,
                ctxBar,
                ctxPie,
                optionsLine,
                optionsBar,
                optionsPie,
                configLine,
                configBar,
                configPie,
                lineChart;
            barChart, pieChart;
            // DOM is ready
            $(function () {
                drawLineChart(); // Line Chart
                drawBarChart(); // Bar Chart
                drawPieChart(); // Pie Chart

                $(window).resize(function () {
                    updateLineChart();
                    updateBarChart();                
                });
            })
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Training/Views/Student/Create.cshtml
@model Student
<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Thêm em vô đi anh yêu :</p>
<div class="container-fluid">
    <div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px" >
        <form asp-action="Create" method="post">
            @* <input type="hidden" name="requestpath" id="requestpath"  /> *@
            <div class="form-group row ">
                <label asp-for="MaSV" class="col-md-4"></label>
                <div class="col-md-5">
                    <input  asp-for="MaSV" style="width: 200px"class="form-control" type="text" placeholder="Nhập Mã sinh viên"required />
                </div>
                   
            </div>
          
            <div class="form-group row">
                <label asp-for="HoTen" class="col-md-4"></label>
                <div class="col-md-5">
                    <input asp-for="HoTen" style="width: 200px"class="form-control" type="text" placeholder="Nhập Họ tên" required />
                </div>
                   
            </div>
                
            <div class="form-group ">
                <input class="btn btn-primary" type="submit" value="Create"style="margin-right: 10px; border-radius: 5px" />
                <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
            </div>
        
        </form>
    </div>
</div>

Training/Views/Student/Delete.cshtml
@model Student

<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Anh muốn xóa em sao ?</p>
<div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px">
    <dl class="row" >
        <dt class="col-md-4" style="color: #fff">
            @Html.DisplayNameFor(model => model.MaSV)
        </dt>
        <dd class="col-md-5"style="color: #fff">
            @Html.DisplayFor(model => model.MaSV)
        </dd>
        <dt class="col-md-4"style="color: #fff">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class="col-md-5"style="color: #fff">
            @Html.DisplayFor(item => item.HoTen)
        </dd>
    </dl>
    <div style="padding: 10px 0">
        <div >
            <form asp-action="Delete" >
                <input  asp-for="Id" type="hidden"  />
                <input class="btn btn-primary" type="submit" value="Delete" style="border-radius: 5px; margin-right: 10px;"  />
                <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
            </form>
        </div>
    
    </div>
</div>

Training/Views/Student/Edit.cshtml
@model Student

<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Anh muốn thay đổi em sao, anh không còn yêu em à ?</p>
@* <form> *@
<div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px" >
    <div style=" width: 100%" >
        <form asp-action="Edit" method="post" >
            <div class="form-group row ">
                <label asp-for="MaSV" class="col-md-4"></label>
                <div class="col-md-8">
                    <input  asp-for="MaSV" style="width: 200px"class="form-control" type="text"  />
                </div>
                   
            </div>
            <div class="form-group row">
                <label asp-for="HoTen" class="col-md-4"></label>
                <div class="col-md-8">
                    <input asp-for="HoTen" style="width: 200px"class="form-control" type="text" />
                </div>
                   
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group " style="padding-top: 20px">
                <input class="btn btn-primary" type="submit" value="Update" style="margin-right: 10px; border-radius: 5px"  />
                <a class="btn btn-primary" asp-action="Index"style=" border-radius: 5px" >Cancel</a>   
            </div>
        </form>
    </div>
</div>
@* </form> *@

Training/Views/Student/GetAllId.cshtml
@model IEnumerable<Student>

@{
    ViewData["Title"] = "Hello anh đẹp trai";
}

<h1>@ViewData["Title"]</h1>

<p style="text-align: left">Thêm sinh viên mới</p>

Training/Views/Student/Index.cshtml
@model IEnumerable<Student>

@{
    ViewData["Title"] = "Hello anh đẹp trai";
}


<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Danh sách sinh viên</h1>

 <div >
          <div class="tm-bg-primary-dark tm-block tm-block-products">
            <div class="tm-product-table-container">
              <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                  <tr>
                      <th scope="col">&nbsp;</th>
                    <th scope="col"style="text-transform: uppercase">@Html.DisplayNameFor(model => model.MaSV)</th>
                    <th scope="col"style="text-transform: uppercase">@Html.DisplayNameFor(model => model.HoTen)</th>
                      <th scope="col">&nbsp;</th>
                  </tr>
                </thead>
                  <tbody>
                  @foreach (var item in Model)
                  {
                      <tr>
                          <td scope="col">&nbsp;</td>
                          <td>
                              @Html.DisplayFor(modelItem => item.MaSV)
                          </td>
                          <td>
                              @Html.DisplayFor(modelItem => item.HoTen)
                          </td>
                          <td>
                              <a asp-action="Edit" asp-route-id="@item.Id" class="tm-product-delete-link" style="margin-right: 10px;">
                                  <i class="fa fa-pencil"></i>
                              </a>
                              <a asp-action="Delete" asp-route-id="@item.Id" class="tm-product-delete-link">
                                  <i class="fa fa-trash"></i>
                              </a>
                          </td>
                      </tr>
                  }
                  </tbody>
              </table>
            </div>
            <!-- table container -->
            <a asp-action="Create"  class="btn btn-primary btn-block text-uppercase mb-3">Add new student <i class="fa fa-user-plus" style="font-size: 20px; "></i>
                </a>
          
          </div>
    </div>

Training/Views/User/Create.cshtml
<h1 style="color: #fff; padding: 15px 0; font-weight: 900">Hello anh đẹp trai</h1>
<p style="text-align: left; color: #fff;">Thêm em vô đi anh yêu :</p>
<div class="container-fluid">
    <div style="background: #435c70; box-shadow: 1px 1px 5px 0 #455c71; width: 500px; padding: 25px; margin-bottom: 100px" >
        <form asp-action="Create" method="post">
            @* <input type="hidden" name="requestpath" id="requestpath"  /> *@
            <div class="form-group row ">
                <label  class="col-md-4">Mã sinh viên : </label>
                <div class="col-md-5">
                    <input name="MaSV"  style="width: 200px"class="form-control" type="text" placeholder="Nhập Mã sinh viên"required />
                </div>
                   
            </div>
          
            <div class="form-group row">
                <label  class="col-md-4">Họ tên :</label>
                <div class="col-md-5">
                    <input name="HoTen"  style="width: 200px"class="form-control" type="text" placeholder="Nhập Họ tên" required />
                </div> 
            </div>
            <div class="form-group row ">
                <label  class="col-md-4"> Mã lớp </label>
                <div class="col-md-5">
                    <input  name="MaLop" style="width: 200px"class="form-control" type="password" placeholder="Nhập Lớp"required />
                </div>
                   
            </div>
          
            <div class="form-group row">
                <label class="col-md-4"> Tên Lớp</label>
                <div class="col-md-5">
                    <input name="TenLop" style="width: 200px"class="form-control" type="text" placeholder="Nhập Họ tên" required />
                </div> 
            </div>   
            <div class="form-group ">
                <input class="btn btn-primary" type="submit" value="Create"style="margin-right: 10px; border-radius: 5px" />
                 
            </div>
        
        </form>
    </div>
</div>